on:
  push:
    branches:
      - main
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}

      - name: Build the Docker Image
        run: |
          DOCKER_TAG="${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/hobby-log:${{ github.sha }}"
          docker build . -t $DOCKER_TAG
          echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV

      - name: Push the Docker Image
        run: docker push $DOCKER_TAG

      - uses: actions/checkout@v4
        with:
          repository: khoutz182/argocd-gitops
          path: argocd-gitops
          ssh-key: ${{ secrets.GH_ARGO_GITOPS_PRIVATE_KEY }}

      - run: |
          cd argocd-gitops
          kubectl patch --local -f apps/user-apps/hobby-log/deploy.yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"hobby-log","image":"${{ env.DOCKER_TAG }}"}]}}}}' -o yaml >! new_deploy.yaml
          mv new_deploy.yaml apps/user-apps/hobby-log/deploy.yaml
          git add apps/user-apps/hobby-log/deploy.yaml -m "Update hobby log to ${{ env.DOCKER_TAG }}"
          git push
